# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cache.proto',
  package='',
  serialized_pb=_b('\n\x0b\x63\x61\x63he.proto\"\xee\x01\n\tTowerCash\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.TowerCash.Entry\x1a.\n\x05\x42lock\x12\x0b\n\x03x10\x18\x01 \x02(\x05\x12\x0b\n\x03w10\x18\x02 \x02(\x05\x12\x0b\n\x03h10\x18\x03 \x02(\x05\x1a\x8d\x01\n\x05\x45ntry\x12\x1e\n\x04plan\x18\x04 \x03(\x0b\x32\x10.TowerCash.Block\x12\x0e\n\x06height\x18\x05 \x02(\x02\x12\x11\n\tstability\x18\x06 \x02(\x02\x12\x0c\n\x04\x61rea\x18\x07 \x02(\x02\x12\x0e\n\x06length\x18\x08 \x02(\x02\x12\x10\n\x08overpass\x18\t \x02(\x02\x12\x11\n\tstaircase\x18\n \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TOWERCASH_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='TowerCash.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x10', full_name='TowerCash.Block.x10', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w10', full_name='TowerCash.Block.w10', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h10', full_name='TowerCash.Block.h10', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=110,
)

_TOWERCASH_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='TowerCash.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plan', full_name='TowerCash.Entry.plan', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='TowerCash.Entry.height', index=1,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stability', full_name='TowerCash.Entry.stability', index=2,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='TowerCash.Entry.area', index=3,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='TowerCash.Entry.length', index=4,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overpass', full_name='TowerCash.Entry.overpass', index=5,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='staircase', full_name='TowerCash.Entry.staircase', index=6,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=254,
)

_TOWERCASH = _descriptor.Descriptor(
  name='TowerCash',
  full_name='TowerCash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='TowerCash.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TOWERCASH_BLOCK, _TOWERCASH_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=254,
)

_TOWERCASH_BLOCK.containing_type = _TOWERCASH
_TOWERCASH_ENTRY.fields_by_name['plan'].message_type = _TOWERCASH_BLOCK
_TOWERCASH_ENTRY.containing_type = _TOWERCASH
_TOWERCASH.fields_by_name['entries'].message_type = _TOWERCASH_ENTRY
DESCRIPTOR.message_types_by_name['TowerCash'] = _TOWERCASH

TowerCash = _reflection.GeneratedProtocolMessageType('TowerCash', (_message.Message,), dict(

  Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
    DESCRIPTOR = _TOWERCASH_BLOCK,
    __module__ = 'cache_pb2'
    # @@protoc_insertion_point(class_scope:TowerCash.Block)
    ))
  ,

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _TOWERCASH_ENTRY,
    __module__ = 'cache_pb2'
    # @@protoc_insertion_point(class_scope:TowerCash.Entry)
    ))
  ,
  DESCRIPTOR = _TOWERCASH,
  __module__ = 'cache_pb2'
  # @@protoc_insertion_point(class_scope:TowerCash)
  ))
_sym_db.RegisterMessage(TowerCash)
_sym_db.RegisterMessage(TowerCash.Block)
_sym_db.RegisterMessage(TowerCash.Entry)


# @@protoc_insertion_point(module_scope)
