#!/bin/bash

# Summarizes log report files.

module add openmind/singularity

srun --job-name=logReport --output=jobs/logReports --ntasks=1 --mem-per-cpu=5000 --cpus-per-task 1 --time=5:00 --qos=tenenbaum \
  singularity exec -B /om2  sklearn-container.img \
  python bin/logReports.py --experimentsFile official_experiments --logsDirectory jobs \
  &
