#!/bin/bash

# DRY=true will show what's going on but run nothing
DRY="true"

# On OM you probably want something like this:
module load openmind/miniconda/3.9.1
source activate ec
SBATCH="true"
PMAP="12"
TMAP="500"
PRED="30"
TRED="5000"

# Name of your script
PROGRAM="logo.py"

# Arguments for the program, respectively for the maps and the reduce
ARGSMAP="-t 600 -g -i 10"
ARGSRED="-t 7200 -i 20 --expandFrontier 2"

# Targets
MAP="none"
#MAP="line square"
REDUCE="all"

# Now let's build the command:
CMD="./map-reduce $PROGRAM"

if [[ "$DRY" = "true" ]]; then
  CMD="$CMD --dry"
fi

if [[ "$SBATCH" = "true" ]]; then
  CMD="$CMD --sbatch $PMAP,$TMAP,$PRED,$TRED"
fi

CMD="$CMD --map $MAP --reduce $REDUCE --argsmap $ARGSMAP --argsreduce $ARGSRED"

# Show it and run it!
printf "\\e[1;34mRunnning\\e[m:\\n%s\\n" "$CMD"
eval "$CMD"
