#!/bin/bash

# Sample script that calls taskRankGraphs.py to create graphs of ECResult metrics from results with a recognitionTaskMetrics dict.
# Note: clustering requires a container with sklearn installed.

module add openmind/singularity

checkpoint0='experimentOutputs/list_aic=1.0_arity=3_BO=True_CO=True_ET=90_HR=0.5_it=5_MF=5_baseline=False_pc=30.0_RT=7200_RW=False_storeTask=True_L=1.0_taskReranker=default_K=2_topkNotMAP=False_rec=True_feat=LearnedFeatureExtractor_graph=True.pickle'
checkpoint1='experimentOutputs/list_aic=1.0_arity=3_BO=True_CO=True_ET=90_HR=0.5_it=20_MF=5_baseline=False_pc=30.0_RT=7200_RW=False_storeTask=True_L=1.0_batch=10_taskReranker=default_K=2_topkNotMAP=False_rec=True_feat=LearnedFeatureExtractor_graph=True.pickle'
checkpoint2='experimentOutputs/list_aic=1.0_arity=3_BO=True_CO=True_ET=90_HR=0.5_it=20_MF=5_baseline=False_pc=30.0_RT=7200_RW=False_storeTask=True_L=1.0_batch=10_taskReranker=random_K=2_topkNotMAP=False_rec=True_feat=LearnedFeatureExtractor_graph=True.pickle'
checkpoint3='experimentOutputs/list_aic=1.0_arity=3_BO=True_CO=True_ET=90_HR=0.5_it=20_MF=5_baseline=False_pc=30.0_RT=7200_RW=False_storeTask=True_L=1.0_batch=10_taskReranker=unsolved_K=2_topkNotMAP=False_rec=True_feat=LearnedFeatureExtractor_graph=True.pickle'

srun --job-name=graphsHeldout$1 --output=data/batch_11_29_2018/tsne --ntasks=1 --mem-per-cpu=5000 --cpus-per-task 1 --time=5:00 --qos=tenenbaum \
  singularity exec -B /om2  sklearn-container.img \
  python taskRankGraphs.py --checkpoints  $checkpoint0 $checkpoint1 $checkpoint2 $checkpoint3 \
  --experimentNames list_baseline list_default_10 list_rand_10 list_unsolved_rand_10 \
  --metricsToPlot heldoutTaskGrammarEntropies --times heldoutTestingTimes --export data/batch_11_29_2018/  \
  &
