#!/bin/bash

module add openmind/singularity

textBenchmark60="experimentOutputs/text_aic=1.0_arity=4_BO=False_ET=60_HR=0.5_it=1_MF=5_baseline=False_pc=30.0_RT=1_L=1.0_taskReranker=default_K=2_topkNotMAP=False_rec=True_feat=LearnedFeatureExtractor.pickle"

srun --job-name=graphs$1 --output=data/taskRankGraphs --ntasks=1 --mem-per-cpu=5000 --cpus-per-task 1 --time=10:00 --qos=tenenbaum \
  singularity exec -B /om2  container.img \
  python taskRankGraphs.py $textBenchmark60 \
  &
