#!/bin/bash

# Sample script that calls taskRankGraphs.py to create graphs of ECResult metrics from results with a recognitionTaskMetrics dict.
# Note: clustering requires a container with sklearn installed.

module add openmind/singularity

graphableCheckpoint='experimentOutputs/list_aic=1.0_arity=4_BO=False_ET=5400_HR=0.5_it=5_MF=5_baseline=False_pc=30.0_RT=7200_storeTaskMetrics=True_L=1.0_taskReranker=default_K=2_topkNotMAP=False_rec=True_feat=LearnedFeatureExtractor_graph=True.pickle'

srun --job-name=graphsHeldout5$1 --output=data/taskRankGraphsHeldout5 --ntasks=1 --mem-per-cpu=5000 --cpus-per-task 1 --time=5:00 --qos=tenenbaum \
  singularity exec -B /om2  sklearn-container.img \
  python taskRankGraphs.py --checkpoints $graphableCheckpoint --metricsToPlot heldoutTaskGrammarEntropies --times heldoutTestingTimes --outlierThreshold 200 --export data \
  &
